version: 0.0
os: linux
files:
  - source: target/java-war-demo.war
    destination: /home/bielei/apache-tomcat-9.0.90/webapps/
hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
#  AfterInstall:
#    - location: Scripts/RunResourceTests.sh
#      timeout: 180
  ApplicationStart:
     - location: before-install
      timeout: 30
      runas: root
      shell: bash
      command: "echo 'Before install hook'"
#    - location: /home/bielei/test.sh
    - location: after-install
      timeout: 3600
      runas: root
      shell: bash
      command: /home/bielei/test.sh
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser
