version: 0.2

phases:
  install:
    commands:
       - yum install -y java-1.8.0-openjdk-devel.x86_64
  pre_build:
    commands:
       - echo build start------------
       - java -version
  build:
    commands:
       - mvn package
  post_build:
    commands:
       - echo build end------------
#      - aws s3 cp target/java-war-demo.war s3://jossbie-california/devops/java-war-demo.war

artifacts:
  files:
#       - '**/*'
    - target/java-war-demo.war
    - Scripts/*
    - appspec.yml
#    name: my-app-release
